
CREATE TABLE IF NOT EXISTS TB_FILME (
ID_FILME INT PRIMARY KEY AUTO_INCREMENT,
NM_FILME VARCHAR(200),
DS_SINOPSE VARCHAR(500),
HR_DURACAO TIME,
DT_LANCAMENTO DATE,
VL_AVALIACAO DECIMAL(2, 1),
NR_CLASSIFICACAO_INDICATIVA INT,
IMG_CAPA VARCHAR(1000),
IMG_BANNER  VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS TB_ATOR (
ID_ATOR INT PRIMARY KEY AUTO_INCREMENT,
NM_ATOR VARCHAR(200),
DT_IDADE DATE
);

CREATE TABLE IF NOT EXISTS TB_FILME_ATOR (
ID_FILME_ATOR INT PRIMARY KEY AUTO_INCREMENT,
ID_FILME INT,
ID_ATOR INT,

FOREIGN KEY (ID_FILME) REFERENCES TB_FILME(ID_FILME),
FOREIGN KEY (ID_ATOR) REFERENCES TB_ATOR(ID_ATOR)
);

CREATE TABLE IF NOT EXISTS TB_GENERO (
ID_GENERO INT PRIMARY KEY AUTO_INCREMENT,
NM_GENERO VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS TB_GENERO_FILME (
ID_GENERO_FILME INT PRIMARY KEY AUTO_INCREMENT,
ID_FILME INT,
ID_GENERO INT,
FOREIGN KEY (ID_FILME) REFERENCES TB_FILME(ID_FILME),
FOREIGN KEY (ID_GENERO) REFERENCES TB_GENERO(ID_GENERO)
);

CREATE TABLE TB_USUARIO (
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
NM_USUARIO VARCHAR(200),
DS_EMAIL VARCHAR(200),
DS_SENHA VARCHAR(200)
);

CREATE TABLE TB_COMENTARIO (
ID_COMENTARIO INT PRIMARY KEY AUTO_INCREMENT,
ID_FILME INT,
ID_USUARIO INT,
DS_COMENTARIO VARCHAR(400),
DT_COMENTARIO DATE,
FOREIGN KEY (ID_FILME) REFERENCES TB_FILME(ID_FILME),
FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)

);
CREATE TABLE TB_FAVORITO (
ID_FAVORITO INT PRIMARY KEY AUTO_INCREMENT,
ID_FILME INT,
ID_USUARIO INT,
FOREIGN KEY (ID_FILME) REFERENCES TB_FILME(ID_FILME),
FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_AVALIACAO_USUARIO_FILME (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_FILME INT,
    NOTA DECIMAL(2, 1),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_FILME) REFERENCES TB_FILME(ID_FILME)
);

